/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TubesPBO;

import java.sql.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class Bayar extends javax.swing.JFrame {
    int no;
    int saldo;
    int saldo_awal;
    private Connection conn;
    private Statement stat;
    private PreparedStatement ps;
    
    java.util.Date tglsekarang = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private final String date = smpdtfmt.format(tglsekarang);
    
    /**
     * Creates new form Bayar
     */
    public Bayar() {
        initComponents();
        open_db();
        tgl1.setText(date);
        setJam();
        Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    }
    
    public final void setJam(){
    ActionListener taskPerformer = new ActionListener() {

        public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";

            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();

            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";

            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);

            waktu.setText(jam+":"+menit+":"+detik+"");
        }
    };
    
    new Timer(1000, taskPerformer).start();
    }
    
    private void open_db() {
        try {
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost/gapaytera", "root", "");
            Statement stm = Con.createStatement();

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Koneksi gagal");
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        waktu = new javax.swing.JLabel();
        tgl1 = new javax.swing.JLabel();
        id_kartu = new javax.swing.JTextField();
        pass_kartu = new javax.swing.JPasswordField();
        tanggal = new javax.swing.JTextField();
        nominal = new javax.swing.JTextField();
        TBayar = new javax.swing.JButton();
        TBatal = new javax.swing.JButton();
        TCetak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fstruk = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(428, 504));
        getContentPane().setLayout(null);

        waktu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setText("tanggal");
        getContentPane().add(waktu);
        waktu.setBounds(510, 100, 130, 20);

        tgl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tgl1.setForeground(new java.awt.Color(255, 255, 255));
        tgl1.setText("tanggal");
        getContentPane().add(tgl1);
        tgl1.setBounds(190, 100, 150, 20);

        id_kartu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(id_kartu);
        id_kartu.setBounds(40, 260, 310, 40);

        pass_kartu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_kartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_kartuActionPerformed(evt);
            }
        });
        getContentPane().add(pass_kartu);
        pass_kartu.setBounds(40, 340, 310, 40);

        tanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tanggal);
        tanggal.setBounds(40, 500, 310, 40);

        nominal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(nominal);
        nominal.setBounds(40, 420, 310, 40);

        TBayar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TBayar.setForeground(new java.awt.Color(102, 102, 0));
        TBayar.setText("BAYAR");
        TBayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBayarActionPerformed(evt);
            }
        });
        getContentPane().add(TBayar);
        TBayar.setBounds(50, 580, 100, 40);

        TBatal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TBatal.setForeground(new java.awt.Color(102, 102, 0));
        TBatal.setText("BATAL");
        TBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBatalActionPerformed(evt);
            }
        });
        getContentPane().add(TBatal);
        TBatal.setBounds(260, 580, 90, 40);

        TCetak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TCetak.setForeground(new java.awt.Color(102, 102, 0));
        TCetak.setText("CETAK");
        TCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCetakActionPerformed(evt);
            }
        });
        getContentPane().add(TCetak);
        TCetak.setBounds(160, 580, 90, 40);

        fstruk.setColumns(20);
        fstruk.setRows(5);
        jScrollPane2.setViewportView(fstruk);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(460, 260, 290, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesPBO/image/Payment.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 650);

        setSize(new java.awt.Dimension(809, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pass_kartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_kartuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_kartuActionPerformed


    public void CekPass(){
            try{
                conn = DriverManager.getConnection("jdbc:mysql://localhost/gapaytera","root","");
                Statement stat = conn.createStatement();
                ResultSet RaUser = stat.executeQuery("SELECT * FROM aktivasikartu WHERE ID_Kartu ='"+id_kartu.getText()+ "'And Password_Kartu='"+pass_kartu.getText()+"'");
                if(RaUser.next()){
                    Bayar();
                }else{
                    JOptionPane.showMessageDialog(null, "Maaf ID_Kartu atau Password salah!", "Login Karyawan", JOptionPane.INFORMATION_MESSAGE);
                    pass_kartu.setText("");
                    tanggal.setText("");
                    id_kartu.setText("");
                    nominal.setText("");
                    fstruk.setText("");
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Koneksi Gagal!", "Informasi", JOptionPane.WARNING_MESSAGE);
            }
    }       
    private void TBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBayarActionPerformed
        tanggal.setText(date);
        CekPass();
    }//GEN-LAST:event_TBayarActionPerformed

    private void TBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBatalActionPerformed
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_TBatalActionPerformed

    private void TCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCetakActionPerformed
        try {
            new Bayar().printComponents(null);
            fstruk.print();
            jTextArea1.setText("");
            id_kartu.setText("");
        } catch (Exception e) {
            dispose();
        }
    }//GEN-LAST:event_TCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bayar().setVisible(true);
            }
        });
    }
    
    public void cekSaldo(){
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance(); 
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gapaytera", "root", "");
            stat = conn.createStatement();
            String sql="select * from aktivasikartu where "+ "ID_Kartu='" +id_kartu.getText() +"'";
            ResultSet RUser = stat.executeQuery(sql); 
            
            if(RUser.next()){
                saldo = RUser.getInt(3);
                //JOptionPane.showMessageDialog(null, "SALDO SEBELUMNYA ADALAH Rp."+saldo, "CEK SALDO Ga-PayTera", JOptionPane.INFORMATION_MESSAGE);               
            }else{
                JOptionPane.showMessageDialog(null, "DATA TIDAK DITEMUKAN", "CEK SALDO Ga-PayTera" , JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void cetakBukti(){
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gapaytera", "root", "");
            stat = (com.mysql.jdbc.Statement) conn.createStatement();
            
            String sql ="SELECT * FROM aktivasikartu WHERE "+ "ID_Kartu='" +id_kartu.getText()+"'";
            ResultSet RUser = stat.executeQuery(sql);
            
            if (RUser.next()){
                fstruk.setText("\n|================================|"+
                "\n           STRUK PEMBAYARAN GALERI\t"+
                "\n JL. Terusan Ryacudu, Way Hui, Jati Agung"+
                "\n                Way Huwi, Lampung Selatan"+
                "\n         INSTITUT TEKNOLOGI SUMATERA"+
                "\n|================================|"+
                "\n" +
                "\n       ID Kartu\t\t : " + RUser.getString(1)+
                "\n       Saldo Awal\t : " + saldo_awal+                        
                "\n       Total Bayar\t : " + nominal.getText()+                        
                "\n       Saldo Akhir\t : " + RUser.getString(3)+
                "\n" + 
                "\n" + 
                "\n       " + waktu.getText()+"  "+tgl1.getText()+
                "\n Terimakasih telah berbelanja di Galeri Itera"+
                "\n|================================|"   
                );
              }else{
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
                fstruk.setText("");
                id_kartu.setText("");
                stat.close();
                conn.close();
        }
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan"+ex);
        }
    }
    
    public void Bayar(){
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gapaytera", "root", "");
            stat = (com.mysql.jdbc.Statement) conn.createStatement();
            
            String sql ="SELECT * FROM aktivasikartu WHERE "+ "ID_Kartu='" +id_kartu.getText()+"'";
            ResultSet RUser = stat.executeQuery(sql);
            if(RUser.next()){
                saldo_awal=RUser.getInt(3);
            }
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
        cekSaldo();
        String id = id_kartu.getText();
            String keluaran = nominal.getText();
            
            int kurang = Integer.parseInt(keluaran);
            
            if(saldo >= kurang){
                try{
                    kurang = saldo-kurang;
                    conn = DriverManager.getConnection("jdbc:mysql://localhost/gapaytera","root","");
                    stat = conn.createStatement();
                    String update = "UPDATE aktivasikartu SET Saldo='"+kurang+"'WHERE ID_Kartu='"+id+"'";
                    ps = conn.prepareStatement(update);
                    ps.execute(update);
                    JOptionPane.showMessageDialog(null, "PEMBAYARAN SUKSES..", "PAYMENT with Ga-PayTera", JOptionPane.INFORMATION_MESSAGE);
                    CatatBayar();
                    cetakBukti();
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, "GAGAL MELAKUKAN PEMBAYARAN!", "PAYMENT with Ga-PayTera", JOptionPane.INFORMATION_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "SALDO KAMU KURANG.. SILAHKAN ISI ULANG!", "PAYMENT with Ga-PayTera", JOptionPane.INFORMATION_MESSAGE);
                new Menu().setVisible(true);
                this.dispose();
            }        
    }
    
    public void CatatBayar(){
        CekTransaksi();
        String tgl = tanggal.getText();
        String keluaran = nominal.getText();
        int i=1;
        try{
            i=i+no;
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gapaytera","root","");
            Statement stat = conn.createStatement();
            String in = "INSERT INTO pendapatan VALUES("+i+",'"+tgl+"','"+keluaran+"')";
            stat.executeUpdate(in);
            JOptionPane.showMessageDialog(null, "PEMBAYARAN BERHASIL DICATAT", "PAYMENT with Ga-PayTera", JOptionPane.INFORMATION_MESSAGE);             
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Koneksi Gagal!", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void CekTransaksi(){
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gapaytera","root","");
            Statement stat = conn.createStatement();
            ResultSet RaUser = stat.executeQuery("SELECT * FROM pendapatan WHERE No_Transaksi IN(SELECT MAX(No_Transaksi) FROM pendapatan)");
            if(RaUser.next()){
                no = RaUser.getInt(1);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Koneksi Gagal!", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TBatal;
    private javax.swing.JButton TBayar;
    private javax.swing.JButton TCetak;
    private javax.swing.JTextArea fstruk;
    private javax.swing.JTextField id_kartu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nominal;
    private javax.swing.JPasswordField pass_kartu;
    private javax.swing.JTextField tanggal;
    private javax.swing.JLabel tgl1;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
