
package TubesPBO;

import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class CariCivitas extends javax.swing.JFrame {
    java.util.Date tglsekarang = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private final String date = smpdtfmt.format(tglsekarang);
    public CariCivitas() {
        initComponents();
        tgl1.setText(date);
        setJam();
        Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public final void setJam(){
    ActionListener taskPerformer = new ActionListener() {

        public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";

            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();

            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";

            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);

            waktu.setText(jam+":"+menit+":"+detik+"");
        }
    };
    
    new Timer(1000, taskPerformer).start();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TCari = new javax.swing.JButton();
        id_civitas = new javax.swing.JTextField();
        TBatal = new javax.swing.JButton();
        tgl1 = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(360, 400));
        getContentPane().setLayout(null);

        TCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesPBO/image/cari2.png"))); // NOI18N
        TCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariActionPerformed(evt);
            }
        });
        getContentPane().add(TCari);
        TCari.setBounds(470, 290, 90, 90);

        id_civitas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_civitas.setBorder(null);
        id_civitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_civitasActionPerformed(evt);
            }
        });
        getContentPane().add(id_civitas);
        id_civitas.setBounds(70, 310, 440, 60);

        TBatal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TBatal.setForeground(new java.awt.Color(153, 0, 0));
        TBatal.setText("BATAL");
        TBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBatalActionPerformed(evt);
            }
        });
        getContentPane().add(TBatal);
        TBatal.setBounds(230, 520, 110, 50);

        tgl1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        tgl1.setForeground(new java.awt.Color(255, 255, 255));
        tgl1.setText("tanggal");
        getContentPane().add(tgl1);
        tgl1.setBounds(60, 220, 150, 20);

        waktu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setText("jam");
        getContentPane().add(waktu);
        waktu.setBounds(440, 220, 110, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesPBO/image/Cari_Civitas.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 680);

        setSize(new java.awt.Dimension(576, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_civitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_civitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_civitasActionPerformed

    private void TCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariActionPerformed
        
        try{
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/gapaytera","root","");
            Statement stat = koneksi.createStatement();
            ResultSet RaUser = stat.executeQuery("SELECT * FROM aktivasikartu WHERE No_Identitas='"+id_civitas.getText()+"'");
            System.out.println("Data Is Exist");
            if(RaUser.next()){
                JOptionPane.showMessageDialog(null,"ANDA SUDAH MEMILIKI KARTU","Cari Civitas",JOptionPane.WARNING_MESSAGE);
                id_civitas.setText("");
            }else{
                Cari_Akun();
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }        
    }//GEN-LAST:event_TCariActionPerformed

    private void TBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBatalActionPerformed
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_TBatalActionPerformed

    public void Cari_Akun(){
            try{
                Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/gapaytera","root","");
                Statement stat = koneksi.createStatement();
                ResultSet RaUser = stat.executeQuery("SELECT * FROM datacivitas WHERE No_Identitas='"+id_civitas.getText()+"'");
                System.out.println("Koneksi Berhasil..");

                if(RaUser.next()){
                    JOptionPane.showMessageDialog(null, "DATA DITEMUKAN", "Cari Civitas", JOptionPane.INFORMATION_MESSAGE);
                    String nim2;
                    new AktivasiKartu(id_civitas.getText()).setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "DATA TIDAK DITEMUKAN", "Cari Civitas", JOptionPane.INFORMATION_MESSAGE);
                    id_civitas.setText("");
                    id_civitas.requestFocus();
                    }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Koneksi Gagal!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariCivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariCivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariCivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariCivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariCivitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TBatal;
    private javax.swing.JButton TCari;
    private javax.swing.JTextField id_civitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tgl1;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
