/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TubesPBO;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class CariCivitas extends javax.swing.JFrame {

    /**
     * Creates new form CariCivitas2
     */
    public CariCivitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TCari = new javax.swing.JButton();
        id_civitas = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(360, 400));
        getContentPane().setLayout(null);

        TCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesPBO/image/cari2.png"))); // NOI18N
        TCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariActionPerformed(evt);
            }
        });
        getContentPane().add(TCari);
        TCari.setBounds(470, 290, 90, 90);

        id_civitas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_civitas.setBorder(null);
        id_civitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_civitasActionPerformed(evt);
            }
        });
        getContentPane().add(id_civitas);
        id_civitas.setBounds(60, 300, 450, 70);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("BATAL");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 520, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesPBO/image/Cari_Civitas.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 680);

        setSize(new java.awt.Dimension(576, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_civitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_civitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_civitasActionPerformed

    private void TCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariActionPerformed
        try{
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/gapaytera","root","");
            Statement stat = koneksi.createStatement();
            ResultSet RaUser = stat.executeQuery("SELECT * FROM datacivitas WHERE No_Identitas='"+id_civitas.getText()+"'");
            System.out.println("Koneksi Berhasil..");
        
            if(RaUser.next()){
                JOptionPane.showMessageDialog(null, "DATA DITEMUKAN", "Cari Civitas", JOptionPane.INFORMATION_MESSAGE);
                new AktivasiKartu().setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "DATA TIDAK DITEMUKAN", "Cari Civitas", JOptionPane.INFORMATION_MESSAGE);
                id_civitas.setText("");
                id_civitas.requestFocus();
                }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Koneksi Gagal!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TCariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariCivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariCivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariCivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariCivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariCivitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TCari;
    private javax.swing.JTextField id_civitas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
